/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_JniLib */

#ifndef _Included_com_JniLib
#define _Included_com_JniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_JniLib
 * Method:    getCurrentPosition
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_JniLib_getCurrentPosition
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_JniLib
 * Method:    setCurrentPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_JniLib_setCurrentPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_JniLib
 * Method:    getFileLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_JniLib_getFileLength
  (JNIEnv *, jobject);

/*
 * Class:     com_JniLib
 * Method:    getGrainRange
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_JniLib_getGrainRange
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_JniLib
 * Method:    setGrainRange
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_JniLib_setGrainRange
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_JniLib
 * Method:    startGrainSynth
 * Signature: (Ljava/lang/String;IIIIIIF)V
 */
JNIEXPORT void JNICALL Java_com_JniLib_startGrainSynth
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jfloat);

/*
 * Class:     com_JniLib
 * Method:    stopGrainSynth
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_JniLib_stopGrainSynth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
